// flow-typed signature: 79d906a6c77284f9bf6d96ac1cc9cb96
// flow-typed version: <<STUB>>/@storybook/blocks_v^8.6.0/flow_v0.261.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/blocks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/blocks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/blocks/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/blocks/dist/index' {
  declare module.exports: $Exports<'@storybook/blocks/dist'>;
}
declare module '@storybook/blocks/dist/index.js' {
  declare module.exports: $Exports<'@storybook/blocks/dist'>;
}
