[files]
extend-exclude = [
    "**/node_modules/**",
    "**/dist/**",
    "**/build/**",
    "**/coverage/**",
    "**/distInfo/**",
    "**/CHANGELOG.md",
    "**/flow-typed/**",
    "packages/eslint-config/build_utils/index.mjs"
]