// flow-typed signature: 0f5c36afff9c1c44f67cf9e6c410cc5d
// flow-typed version: <<STUB>>/redux-thunk_v^3.1.0/flow_v0.261.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-thunk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-thunk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-thunk/dist/redux-thunk.legacy-esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-thunk/dist/redux-thunk.legacy-esm.js' {
  declare module.exports: $Exports<'redux-thunk/dist/redux-thunk.legacy-esm'>;
}
