// flow-typed signature: 54d0158f9a89f3ab87d8bce997f21dc4
// flow-typed version: <<STUB>>/stylelint_v^16.14.1/flow_v0.261.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint' {
  declare module.exports: any;
}
