// flow-typed signature: fce09cf39a6b899d584f87635f9924a8
// flow-typed version: <<STUB>>/@rollup/pluginutils_v^5.1.4/flow_v0.261.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rollup/pluginutils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rollup/pluginutils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@rollup/pluginutils/dist/cjs' {
  declare module.exports: any;
}

declare module '@rollup/pluginutils/dist/es' {
  declare module.exports: any;
}

// Filename aliases
declare module '@rollup/pluginutils/dist/cjs/index' {
  declare module.exports: $Exports<'@rollup/pluginutils/dist/cjs'>;
}
declare module '@rollup/pluginutils/dist/cjs/index.js' {
  declare module.exports: $Exports<'@rollup/pluginutils/dist/cjs'>;
}
declare module '@rollup/pluginutils/dist/es/index' {
  declare module.exports: $Exports<'@rollup/pluginutils/dist/es'>;
}
declare module '@rollup/pluginutils/dist/es/index.js' {
  declare module.exports: $Exports<'@rollup/pluginutils/dist/es'>;
}
