// flow-typed signature: a32bce8887e3db1f05f64b183fe3b538
// flow-typed version: <<STUB>>/@eslint/compat_v^1.2.7/flow_v0.261.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@eslint/compat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@eslint/compat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@eslint/compat/dist/esm' {
  declare module.exports: any;
}

// Filename aliases
declare module '@eslint/compat/dist/esm/index' {
  declare module.exports: $Exports<'@eslint/compat/dist/esm'>;
}
declare module '@eslint/compat/dist/esm/index.js' {
  declare module.exports: $Exports<'@eslint/compat/dist/esm'>;
}
