// flow-typed signature: 309257d6c66b614a9bde70cb0e507173
// flow-typed version: <<STUB>>/postcss-preset-env_v^10.1.5/flow_v0.261.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-preset-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-preset-env' {
  declare module.exports: any;
}
