// flow-typed signature: 0a60f529aa0a4f10a5a839d38db95f4b
// flow-typed version: <<STUB>>/stylelint-config-standard-scss_v^14.0.0/flow_v0.261.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-standard-scss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-standard-scss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'stylelint-config-standard-scss/index' {
  declare module.exports: $Exports<'stylelint-config-standard-scss'>;
}
declare module 'stylelint-config-standard-scss/index.js' {
  declare module.exports: $Exports<'stylelint-config-standard-scss'>;
}
